### ISSUE TITLE
Question about training 

### ISSUE THREAD

**Issue by linQian99** [xuxw98/Online3D#1]
Thank you for your great work! May I ask could you please share the detail of training? How many gpus do you use to train? Thank you for your time.

Best Regards

**Comment by xuxw98** [comment]
Hi! thanks for your interest. 
1. The training consists of two stages: we first train a single-view perception model on SV data, then we insert Memory-based adapters into the network and finetune it on MV data. This repo  contains the training code of the whole pipeline on three tasks.
2. We generally use 2 3090 GPUs for training. It takes about 2 days to train SV model and finetune it on MV data.

**Comment by xuxw98** [comment]
~
